schedules:
- cron: "*/5 * * * *"

stages:
- stage: 'Hosted_Ubuntu_1604'
  dependsOn: []
  jobs:
  - job: 'Test_pip_install_deps'
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
    steps:
    - task: UsePythonVersion@0
      displayName: Use Python $(python.version)
      inputs:
        versionSpec: $(python.version)
    - script: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --ignore-installed -U -q --no-cache-dir tensorflow torch scipy
        python -m pip list
      displayName: 'Install dependencies'