echo "multithread execution"
which pwsh
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1