echo "multithread execution"
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1 &
./download.ps1