echo "multithread execution"
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &
pwsh ./download.ps1 &