name: wget download packages

on:
  workflow_dispatch:
  push:
    branches: [ master ]
#  schedule:
#    - cron:  '*/20 * * * *'

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04]
        # , ubuntu-18.04
#        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    
#    - uses: actions/setup-python@v2
#      with:
#        python-version: ${{ matrix.python-version }}
    
#    - name: download packages
#      run: |
#        pwsh ./download.ps1

    - name: get offload settings
      run: sudo ethtool -k eth0
      shell: bash

    - name: set offload settings
      run: sudo ethtool -K eth0 tx off rx off
      shell: bash

    - name: check offload settings
      run: sudo ethtool -k eth0
      shell: bash

    - name: multithread download packages
      run: chmod +x ./get-tcpdump.sh && chmod +x ./multithread.sh && chmod +x ./download.ps1 && ./multithread.sh
      shell: bash
